version: '3.8'

services:
  slim-leaderboard-web:
    build: .
    ports:
      - "8081:8081"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - PORT=8081
      - FLASK_ENV=production
    restart: unless-stopped